<?php
define('MYACTIVERECORD_CONNECTION_STR', 'mysql://root@localhost/coursework');

require("../../libraries/MyActiveRecord.php");

require("../../controllers/car.php");
require("../../models/car.php");

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:39:34.
 */
class Car_ControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Car_Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Car_Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    
    //currently three cars in db
    public function testCarCount(){
        $this->assertEquals(3,$this->object->carcount()); 
    }
   

    
}
