<?php
define('SERVER_ROOT', 'c:\xampp\htdocs\cw01');
define('MYACTIVERECORD_CONNECTION_STR', 'mysql://root@localhost/coursework');

require("../../libraries/MyActiveRecord.php");

require("../../controllers/users.php");
require("../../models/users.php");
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:40:12.
 */
class Users_ControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Users_Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Users_Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

     public function testUserCount()
   {
       $this->assertEquals(7,$this->object->count());
   }
    
 /*  public function testAdd(){
     
        $simulatedGetVars['username']="testuser";
        $simulatedGetVars['password']="123";
        $simulatedGetVars['firstname']="test firstname";
        $simulatedGetVars['secondname']="test secondname";
        $simulatedGetVars['firstname']="test firstname";
        $simulatedGetVars['address']="test address";
        $simulatedGetVars['type']=2;
        $this->assertTrue($this->object->add($simulatedGetVars));  
   }
  * 
  */
   
   public function testDelete()
   {
       $simulatedGetVars['id']=17;
        $this->assertTrue($this->object->delete($simulatedGetVars));  
   }
   
  
   
}
