<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 18:12:10.
 */
class Content_ModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Content_Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Content_Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Content_Controller::add
     * @todo   Implement testAdd().
     */
    public function testget_article() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
        /**
     * @covers Content_Controller::add
     * @todo   Implement testAdd().
     */
    public function testget_articlecount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
        /**
     * @covers Content_Controller::add
     * @todo   Implement testAdd().
     */
    public function testget_articles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }



   
}
