<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 18:13:31.
 */
class MyActiveRecordTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MyActiveRecord
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MyActiveRecord;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MyActiveRecord::Connection
     * @todo   Implement testConnection().
     */
    public function testConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Query
     * @todo   Implement testQuery().
     */
    public function testQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::DbDate
     * @todo   Implement testDbDate().
     */
    public function testDbDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::DbDateTime
     * @todo   Implement testDbDateTime().
     */
    public function testDbDateTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::TimeStamp
     * @todo   Implement testTimeStamp().
     */
    public function testTimeStamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Tables
     * @todo   Implement testTables().
     */
    public function testTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::DistinctValues
     * @todo   Implement testDistinctValues().
     */
    public function testDistinctValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::TableExists
     * @todo   Implement testTableExists().
     */
    public function testTableExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Class2Table
     * @todo   Implement testClass2Table().
     */
    public function testClass2Table() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Columns
     * @todo   Implement testColumns().
     */
    public function testColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::GetType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::GetLen
     * @todo   Implement testGetLen().
     */
    public function testGetLen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::AllowNull
     * @todo   Implement testAllowNull().
     */
    public function testAllowNull() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Escape
     * @todo   Implement testEscape().
     */
    public function testEscape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::GetLinkTable
     * @todo   Implement testGetLinkTable().
     */
    public function testGetLinkTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Link
     * @todo   Implement testLink().
     */
    public function testLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::UnLink
     * @todo   Implement testUnLink().
     */
    public function testUnLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Count
     * @todo   Implement testCount().
     */
    public function testCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::FindBySql
     * @todo   Implement testFindBySql().
     */
    public function testFindBySql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::FindAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::FindFirst
     * @todo   Implement testFindFirst().
     */
    public function testFindFirst() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::FindById
     * @todo   Implement testFindById().
     */
    public function testFindById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::FreqDist
     * @todo   Implement testFreqDist().
     */
    public function testFreqDist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Begin
     * @todo   Implement testBegin().
     */
    public function testBegin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::RollBack
     * @todo   Implement testRollBack().
     */
    public function testRollBack() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::Commit
     * @todo   Implement testCommit().
     */
    public function testCommit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::populate
     * @todo   Implement testPopulate().
     */
    public function testPopulate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::add_child
     * @todo   Implement testAdd_child().
     */
    public function testAdd_child() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::attach
     * @todo   Implement testAttach().
     */
    public function testAttach() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::detach
     * @todo   Implement testDetach().
     */
    public function testDetach() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::set_attached
     * @todo   Implement testSet_attached().
     */
    public function testSet_attached() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::set_date
     * @todo   Implement testSet_date().
     */
    public function testSet_date() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::set_datetime
     * @todo   Implement testSet_datetime().
     */
    public function testSet_datetime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::get_timestamp
     * @todo   Implement testGet_timestamp().
     */
    public function testGet_timestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::find_parent
     * @todo   Implement testFind_parent().
     */
    public function testFind_parent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::find_children
     * @todo   Implement testFind_children().
     */
    public function testFind_children() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::find_linked
     * @todo   Implement testFind_linked().
     */
    public function testFind_linked() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::find_attached
     * @todo   Implement testFind_attached().
     */
    public function testFind_attached() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::distinct_values
     * @todo   Implement testDistinct_values().
     */
    public function testDistinct_values() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::count_children
     * @todo   Implement testCount_children().
     */
    public function testCount_children() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::count_linked
     * @todo   Implement testCount_linked().
     */
    public function testCount_linked() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::find_siblings
     * @todo   Implement testFind_siblings().
     */
    public function testFind_siblings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::add_error
     * @todo   Implement testAdd_error().
     */
    public function testAdd_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::get_error
     * @todo   Implement testGet_error().
     */
    public function testGet_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::get_errors
     * @todo   Implement testGet_errors().
     */
    public function testGet_errors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::validate_existence
     * @todo   Implement testValidate_existence().
     */
    public function testValidate_existence() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::validate_regexp
     * @todo   Implement testValidate_regexp().
     */
    public function testValidate_regexp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::validate_uniqueness_of
     * @todo   Implement testValidate_uniqueness_of().
     */
    public function testValidate_uniqueness_of() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::validate_unique_email
     * @todo   Implement testValidate_unique_email().
     */
    public function testValidate_unique_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::validate_email
     * @todo   Implement testValidate_email().
     */
    public function testValidate_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::h
     * @todo   Implement testH().
     */
    public function testH() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyActiveRecord::to_str
     * @todo   Implement testTo_str().
     */
    public function testTo_str() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
